# Generated by Django 4.0.6 on 2022-09-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_teacher_attendance_alter_subjects_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mat_num',
        ),
    ]
