# Generated by Django 4.0.6 on 2022-09-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_studentattendance_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='students',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
