# Generated by Django 4.0.6 on 2023-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_messages_remove_studentattendance_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('github', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
